project_id = "mbxqjjmjywsxibttjrgr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.submit-contact]
    verify_jwt = false
  [functions.submit-lead]
    verify_jwt = false
  [functions.llms-txt]
    verify_jwt = false
  [functions.track-visitor]
    verify_jwt = false
  [functions.generate-sitemap]
    verify_jwt = false
  [functions.ssr-index]
    verify_jwt = false
