/**
 * Supabase service barrel.
 *
 * The actual Supabase client lives in `src/integrations/supabase/client.ts`,
 * which is auto-generated by the Lovable Cloud integration and MUST NOT be
 * moved or edited. This file re-exports it under the canonical
 * `@/services/...` path used by the rest of the application, so that all
 * "talks-to-the-backend" imports look consistent:
 *
 *   import { supabase } from "@/services/supabase";
 *
 * If you need to add custom database helpers or query functions, put them
 * here (or in a sibling file like `src/services/blogPosts.ts`) — keep raw
 * `supabase.from(...)` calls out of components.
 */

export { supabase } from "@/integrations/supabase/client";
