// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog posts with their slug, title, status and publish date. Optionally filter by status.",
  inputSchema: {
    status: z.enum(["draft", "published", "scheduled"]).optional().describe("Filter by post status."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id, slug, title, status, category, tags, excerpt, published_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post by slug, including its body content and SEO metadata.",
  inputSchema: { slug: z2.string().trim().min(1).describe("The blog post slug, e.g. 'my-first-post'.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").select("id, slug, title, status, category, tags, excerpt, content, meta_title, meta_description, published_at, updated_at").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No blog post found with slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var create_blog_post_default = defineTool3({
  name: "create_blog_post",
  title: "Create blog post draft",
  description: "Create a new blog post. Posts are always created as drafts and must be published from the admin dashboard.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Post title."),
    slug: z3.string().trim().min(1).regex(/^[a-z0-9-]+$/, "Use lowercase letters, numbers and hyphens only.").describe("URL slug."),
    content: z3.string().default("").describe("Post body (HTML or rich text)."),
    excerpt: z3.string().optional().describe("Short summary shown in listings."),
    category: z3.string().optional().describe("Post category."),
    tags: z3.array(z3.string()).optional().describe("Tags for the post.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, slug, content, excerpt, category, tags }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").insert({
      title,
      slug,
      content: content ?? "",
      excerpt: excerpt ?? null,
      ...category ? { category } : {},
      ...tags ? { tags } : {},
      status: "draft"
    }).select("id, slug, title, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Draft created: ${data?.title} (/blog/${data?.slug})` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/update-blog-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var update_blog_post_default = defineTool4({
  name: "update_blog_post",
  title: "Update blog post",
  description: "Update an existing blog post's title, content, excerpt, category, tags or SEO metadata. Identified by slug.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Slug of the post to update."),
    title: z4.string().trim().min(1).optional(),
    content: z4.string().optional(),
    excerpt: z4.string().optional(),
    category: z4.string().optional(),
    tags: z4.array(z4.string()).optional(),
    meta_title: z4.string().optional(),
    meta_description: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = Object.fromEntries(
      Object.entries(fields).filter(([, value]) => value !== void 0)
    );
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "Nothing to update \u2014 supply at least one field." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").update(patch).eq("slug", slug).select("id, slug, title, status, updated_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No blog post found with slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: `Updated ${data.title} (/blog/${data.slug}).` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-pages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_pages_default = defineTool5({
  name: "list_pages",
  title: "List site pages",
  description: "List CMS pages with slug, title, template type and publication status.",
  inputSchema: {
    status: z5.enum(["draft", "published", "scheduled"]).optional().describe("Filter by page status."),
    limit: z5.number().int().min(1).max(100).default(50).describe("Maximum number of pages to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cms_pages").select("id, slug, title, status, template_type, meta_title, meta_description, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^4.4.3";
var list_contacts_default = defineTool6({
  name: "list_contacts",
  title: "List contact enquiries",
  description: "List contact-form enquiries with name, email, company and message, newest first.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).default(25).describe("Maximum number of enquiries to return."),
    search: z6.string().trim().optional().describe("Filter by name, email or company (case-insensitive substring).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contacts").select("id, name, email, company, message, subscribed_to_marketing, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) {
      const term = `%${search}%`;
      query = query.or(`name.ilike.${term},email.ilike.${term},company.ilike.${term}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^4.4.3";
var list_leads_default = defineTool7({
  name: "list_leads",
  title: "List leads",
  description: "List captured leads (lead-magnet downloads) with name, email, company and download history.",
  inputSchema: {
    limit: z7.number().int().min(1).max(100).default(25).describe("Maximum number of leads to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").select("id, full_name, email, company_university, title, marketing_consent, download_history, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mbxqjjmjywsxibttjrgr";
var mcp_default = defineMcp({
  name: "the-magic-coffin-for-silly-vampires",
  title: "The Magic Coffin for Silly Vampires",
  version: "0.1.0",
  instructions: "Tools for The Magic Coffin for Silly Vampires. Read and edit blog posts and CMS pages, and review contact enquiries and captured leads. All tools act as the signed-in admin user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    create_blog_post_default,
    update_blog_post_default,
    list_pages_default,
    list_contacts_default,
    list_leads_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
